# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(518, 327)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(120, 20, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(370, 20, 55, 16))
        self.label_2.setObjectName("label_2")
        self.produkt = QtWidgets.QTextEdit(parent=Dialog)
        self.produkt.setGeometry(QtCore.QRect(20, 50, 246, 31))
        self.produkt.setObjectName("produkt")
        self.lista = QtWidgets.QListWidget(parent=Dialog)
        self.lista.setGeometry(QtCore.QRect(10, 140, 491, 121))
        self.lista.setObjectName("lista")
        self.zapis = QtWidgets.QPushButton(parent=Dialog)
        self.zapis.setGeometry(QtCore.QRect(210, 280, 93, 28))
        font = QtGui.QFont()
        font.setItalic(True)
        self.zapis.setFont(font)
        self.zapis.setStyleSheet("background:rgb(0, 255, 255)")
        self.zapis.setObjectName("zapis")
        self.addbutton = QtWidgets.QPushButton(parent=Dialog)
        self.addbutton.setGeometry(QtCore.QRect(90, 100, 93, 28))
        font = QtGui.QFont()
        font.setItalic(True)
        self.addbutton.setFont(font)
        self.addbutton.setStyleSheet("background:rgb(0, 255, 255)")
        self.addbutton.setObjectName("addbutton")
        self.ilosc = QtWidgets.QTextEdit(parent=Dialog)
        self.ilosc.setGeometry(QtCore.QRect(270, 50, 246, 31))
        self.ilosc.setObjectName("ilosc")
        self.delbutton = QtWidgets.QPushButton(parent=Dialog)
        self.delbutton.setGeometry(QtCore.QRect(330, 100, 93, 28))
        font = QtGui.QFont()
        font.setItalic(True)
        self.delbutton.setFont(font)
        self.delbutton.setStyleSheet("background:rgb(0, 255, 255)")
        self.delbutton.setObjectName("delbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nazwa"))
        self.label_2.setText(_translate("Dialog", "Ilosc"))
        self.zapis.setText(_translate("Dialog", "zapisz"))
        self.addbutton.setText(_translate("Dialog", "Dodaj"))
        self.delbutton.setText(_translate("Dialog", "Usuń"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
